- name: Preconfigure postfix
  shell: bash -c 'debconf-set-selections <<< "postfix postfix/${item.key} string ${item.value}"'
  with_items:
    - {'key': 'mailname', 'value': $mailname}

- name: Install essential packages
  apt: pkg=${item} state=installed
  with_items:
    - bcrypt
    - curl
    - dovecot-imapd
    - dovecot-managesieved
    - dovecot-pop3d
    - dovecot-sieve
    - dovecot-sqlite
    - git
    - logrotate
    # - mail-server^  # Ansible fails on that one.
    - nginx
    - openssh-server
    - php5-cli
    - php5-fpm
    - php5-sqlite
    - postfix
    - postgrey
    - pwgen
    - rsyslog
    - subversion
