- name: Install postfix config files
  copy: src=postfix/${item} dest=/etc/postfix
  with_items:
    - header_checks

- name: Install postfix config templates
  template: src=postfix/${item} dest=/etc/postfix
  with_items:
    - main.cf
    - master.cf
    - ${db_backend}/sql-virtual-alias-maps.cf
    - ${db_backend}/sql-virtual-domains-maps.cf
    - ${db_backend}/sql-virtual-mailbox-maps.cf
