#!/usr/bin/env sh

PROVIDER=$1
CONFIG="$2"

cd /usr/local/share/openvpn/providers/$PROVIDER

if [ -n "$OPENVPN_USERNAME" ] && [ -n "$OPENVPN_PASSWORD" ]
then
    touch auth
    chmod 400 auth
    cat > auth <<EOF
$OPENVPN_USERNAME
$OPENVPN_PASSWORD
EOF
    unset OPENVPN_USERNAME OPENVPN_PASSWORD
fi

if [ ! -e /dev/net/tun ]; then
    mkdir -p /dev/net
    mknod /dev/net/tun c 10 200
fi

exec openvpn "$CONFIG"
